export const clubCategoryMapping: Record<string, string> = {
  ALL: '전체',
  NEW_REGISTRATION: '신규등록',
  TEMPORARY_REGISTRATION: '가등록',
  CULTURE_ARTS: '문예분과',
  SOCIAL: '사회분과',
  RELIGION: '종교분과',
  SPORTS: '체육분과',
  ACADEMIC: '학술분과',
};

export const clubList = [
  { id: 1, name: 'H.P(펌프 및 오락실 동아리)', category: '가등록', isRecruiting: false },
  { id: 2, name: 'SLANG(국제교류)', category: '가등록', isRecruiting: false },
  { id: 3, name: 'PLEIADES(메탈밴드동아리)', category: '가등록', isRecruiting: false },
  { id: 4, name: '크누 모빌리티(모빌리티 동아리)', category: '가등록', isRecruiting: false },
  { id: 5, name: '복현기우회(바둑 동아리)', category: '학술분과', isRecruiting: false },
  { id: 6, name: '한울회(아람단 동아리)', category: '사회분과', isRecruiting: false },
  { id: 7, name: '동그라미(농구 동아리)', category: '체육분과', isRecruiting: false },
  { id: 8, name: 'KUTC(테니스 동아리)', category: '체육분과', isRecruiting: false },
  { id: 9, name: '스트라이크(야구 동아리)', category: '체육분과', isRecruiting: false },
  { id: 10, name: '검도부(검도 동아리)', category: '체육분과', isRecruiting: false },
  { id: 11, name: '오렌지파이터스(미식축구 동아리)', category: '체육분과', isRecruiting: false },
  { id: 12, name: 'KNUBC(볼링 동아리)', category: '체육분과', isRecruiting: false },
  { id: 13, name: 'VINE(영어회화동아리)', category: '학술분과', isRecruiting: false },
  { id: 14, name: 'IZB(인질범)(인라인, 보드 동아리)', category: '체육분과', isRecruiting: false },
  { id: 15, name: '스윙스(배드민턴 동아리)', category: '체육분과', isRecruiting: false },
  { id: 16, name: '업어치기(유도 동아리)', category: '체육분과', isRecruiting: false },
  {
    id: 17,
    name: '앱동(어플리케이션 제작 교육 동아리)',
    category: '학술분과',
    isRecruiting: false,
  },
  { id: 18, name: '연극반(연극 동아리)', category: '문예분과', isRecruiting: false },
  { id: 19, name: '그랜드챕스(밴드 동아리)', category: '문예분과', isRecruiting: false },
  { id: 20, name: 'KNUAO(관현악반)(오케스트라동아리)', category: '문예분과', isRecruiting: false },
  { id: 21, name: '합창단(합창 동아리)', category: '문예분과', isRecruiting: false },
  { id: 22, name: '청음반(통기타 동아리)', category: '문예분과', isRecruiting: false },
  { id: 23, name: '우리노래반(우리노래를 하는 동아리)', category: '문예분과', isRecruiting: false },
  { id: 24, name: '일렉스(밴드 동아리)', category: '문예분과', isRecruiting: false },
  { id: 25, name: '수리영역(봉사동아리)', category: '신규등록', isRecruiting: false },
  { id: 26, name: 'ACE(경제 시사 동아리)', category: '신규등록', isRecruiting: false },
  { id: 27, name: '요리조리(요리 동아리)', category: '문예분과', isRecruiting: false },
  { id: 28, name: 'KGA(골프 동아리)', category: '체육분과', isRecruiting: false },
  { id: 29, name: '사우회(사진 동아리)', category: '문예분과', isRecruiting: false },
  { id: 30, name: '경묵회(서예 동아리)', category: '문예분과', isRecruiting: false },
  { id: 31, name: '꿈틀(영상 창작 동아리)', category: '문예분과', isRecruiting: false },
  { id: 32, name: 'POW(흑인음악 동아리)', category: '문예분과', isRecruiting: false },
  { id: 33, name: '토레스(클래식기타 동아리)', category: '문예분과', isRecruiting: false },
  { id: 34, name: '익스프레션(작사작곡 동아리)', category: '문예분과', isRecruiting: false },
  { id: 35, name: '터프시커리(댄스 동아리)', category: '문예분과', isRecruiting: false },
  { id: 36, name: '쌩목(버스킹)', category: '문예분과', isRecruiting: false },
  { id: 37, name: '크누피(피아노 연주 동아리)', category: '문예분과', isRecruiting: false },
  { id: 38, name: 'KOMO(영화 감상 동아리)', category: '문예분과', isRecruiting: false },
];

export const textColorsByCategory: { [key: string]: string } = {
  NEW_REGISTRATION: 'text-sky-500',
  TEMPORARY_REGISTRATION: 'text-blue-800',
  CULTURE_ARTS: 'text-yellow-800',
  SOCIAL: 'text-red-400',
  RELIGION: 'text-green-800',
  SPORTS: 'text-indigo-400',
  ACADEMIC: 'text-purple-600',
};
